### ISSUE TITLE
US-03: Recommondations

### ISSUE THREAD

**Issue by cgurtner** [cgurtner/ZHAW-PM3#8]
I click on "Nearby" and receive search results within a 1km radius. These are sorted by rating, allowing me to see the best recommendations nearby.

**Comment by cgurtner** [comment]
Nearby search is done; Rating will be added at a later points (rel #11 )

**Comment by cgurtner** [comment]
To-Do:

- Show Rating
- Sort by Rating

**Comment by seitzm97** [comment]
Implemented overall rating, fetched amenity list now sorted by overall rating and the rating is shown as stars.
